name: chat_gpt_02
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: "none"

# App versioning
version: 1.0.0+1

# Flutter SDK version compatibility
environment:
  sdk: ">=3.0.0 <4.0.0"  # ✅ Updated for Flutter 3.x compatibility

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  velocity_x: ^4.3.0
  chat_gpt_sdk: ^2.2.7  # ✅ Updated to latest from pub.dev

# Development dependencies
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Asset files required for the app
  assets:
    - .env
